# Generated by Django 5.2.7 on 2025-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='subdivision',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Контактный телефон'),
        ),
    ]
