# Generated by Django 5.2.7 on 2025-11-04 17:54

import compensations.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_process', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=32, verbose_name='Статус заявки')),
                ('report_year', models.PositiveIntegerField(db_index=True, default=2025, verbose_name='Отчётный год')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to=compensations.models.generated_docx_upload_path, verbose_name='Сформированный документ (.docx)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=512, verbose_name='Название публикации')),
                ('journal_or_source', models.CharField(blank=True, max_length=512, verbose_name='Журнал/Источник публикации')),
                ('indexation', models.CharField(choices=[('scopus', 'Scopus'), ('wos', 'Web of Science')], db_index=True, default='scopus', max_length=16, verbose_name='Индексация')),
                ('quartile', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('N/A', 'Нет/Не указано')], db_index=True, max_length=8, null=True, verbose_name='Квартиль (только для WoS)')),
                ('percentile', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Перцентиль (только для Scopus)')),
                ('doi', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Авторы (список строк)')),
                ('has_university_affiliation', models.BooleanField(default=False, verbose_name='Есть аффилиация университета')),
                ('faculty', models.CharField(blank=True, choices=[('pedagogical_institute', 'Педагогический институт'), ('arts_humanities', 'Высшая школа искусства и гуманитарных наук'), ('it_engineering', 'Высшая школа информационных технологий и инженерии'), ('natural_sciences', 'Высшая школа естественных наук'), ('economics', 'Высшая школа экономики'), ('law', 'Высшая школа права')], db_index=True, max_length=64, verbose_name='Высшая школа')),
                ('site_source', models.CharField(blank=True, max_length=255, verbose_name='Сайт-источник/площадка')),
                ('source_url', models.URLField(blank=True, verbose_name='URL публикации')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=compensations.models.article_upload_path, verbose_name='Файл публикации/подтверждения')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='compensations.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('indexation', 'scopus'), ('percentile__isnull', False), ('quartile__isnull', True)), models.Q(('indexation', 'wos'), ('percentile__isnull', True), ('quartile__isnull', False)), _connector='OR'), name='paper_scopus_wos_fields_exclusive')],
            },
        ),
    ]
