# Generated by Django 5.2.7 on 2025-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='faculty',
        ),
        migrations.AddField(
            model_name='application',
            name='faculty',
            field=models.CharField(blank=True, choices=[('pedagogical_institute', 'Педагогический институт'), ('arts_humanities', 'Высшая школа искусства и гуманитарных наук'), ('it_engineering', 'Высшая школа информационных технологий и инженерии'), ('natural_sciences', 'Высшая школа естественных наук'), ('economics', 'Высшая школа экономики'), ('law', 'Высшая школа права')], db_index=True, max_length=64, null=True, verbose_name='Высшая школа'),
        ),
    ]
