# Generated by Django 5.2.7 on 2025-11-09 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0002_remove_paper_faculty_application_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('subdivision', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('telephone', models.CharField(blank=True, max_length=64, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Соавтор',
                'verbose_name_plural': 'Соавторы',
                'ordering': ['full_name'],
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='paper',
            name='pages',
            field=models.CharField(blank=True, max_length=64, verbose_name='Страницы'),
        ),
        migrations.AddField(
            model_name='paper',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Том'),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='paper',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='papers', to='compensations.coauthor', verbose_name='Соавторы'),
        ),
    ]
