# Generated by Django 5.2.7 on 2025-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0003_coauthor_remove_paper_authors_paper_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coauthor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='site_source',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Сайт-источник/площадка'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='source_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='URL публикации'),
        ),
    ]
