# Generated by Django 5.2.7 on 2025-11-14 06:09

import compensations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0004_alter_coauthor_full_name_alter_paper_site_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file_upload',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=compensations.models.article_upload_path, verbose_name='Файл публикации/подтверждения'),
        ),
    ]
