# Generated by Django 5.2.7 on 2025-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0006_migrate_old_drafts_to_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='submitted', max_length=32, verbose_name='Статус заявки'),
        ),
    ]
