# Generated by Django 5.2.7 on 2025-11-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='submitted', max_length=32, verbose_name='Статус заявки'),
        ),
    ]
